site_name: Agiel

repo_name: "2023.1-Agiel"
repo_url: "https://github.com/Interacao-Humano-Computador/2023.1-Agiel"

theme:
  name: material
  logo: assets/agiel-white.png
  favicon: assets/agiel-white.png
  language: "pt"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Tema claro
  features:
    - navigation.tabs
  font:
    text: "Montserrat"
    code: "sans-serif"

nav:
  - Início: index.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Cronograma Realizado: planejamento/cronograma_realizado.md 
    - Escolha do Site: planejamento/escolha_do_site.md
    - Ferramentas: planejamento/ferramentas_utilizadas.md
    - Processo de Design: planejamento/processo_design.md
    - Reuniões: planejamento/reunioes.md
  - Análise de Requisitos:
    - Análise de Tarefas: requisitos/analise_tarefas.md
    - Aspectos Éticos: requisitos/aspectos_eticos.md
    - Caract. da Plataforma: requisitos/caracteristicas-da-plataforma.md
    - Cenários: requisitos/cenarios.md
    - Guia de Estilo: requisitos/guia_de_estilo.md
    - Metas de Usabilidade: requisitos/metas_usabilidade.md
    - Perfil do Usuário: requisitos/perfil_do_usuario.md
    - Personas: requisitos/personas.md
    - Princípios Gerais de Projeto: requisitos/principios_gerais.md
  - Design Avaliação e Desenvolvimento:
    - Nível 1:
      - Análise de Tarefas:
        - Planejamento da Avaliação: desenvolvimento/tarefas/planejamento_tarefas.md
        - Planejamento do Relato de Resultados: desenvolvimento/tarefas/planejamento_resultado_tarefas.md
        - Relato de Resultados: desenvolvimento/tarefas/relatos_analise_tarefas.md  
      - Storyboard:
        - Planejamento da Avaliação: desenvolvimento/storyboard/planejamento_avaliacao_storyboard.md
        - Planejamento do Relato de Resultados: desenvolvimento/storyboard/planejamento_relato_avaliacao_storyboard.md
        - Relato de Resultados: desenvolvimento/storyboard/relatos_storyboard.md
    - Nível 2:
      - Protótipo de Papel:
        - Planejamento da Avaliação: desenvolvimento/protótipo_de_papel/planejamento_da_avaliação_do_protótipo_de_papel.md
        - Planejamento do Relato de Resultados: desenvolvimento/protótipo_de_papel/planejamento_relato_resultado_prototipo_papel.md
        - Relato de Resultados: desenvolvimento/protótipo_de_papel/relatos_prototipo_papel.md
    - Nível 3:
      - Protótipo de Alta Fidelidade:
        - Planejamento da Avaliação: desenvolvimento/prototipo_alta_fidelidade/planejamento_alta_fidelidade.md
        - Planejamento do Relato de Resultados: desenvolvimento/prototipo_alta_fidelidade/planejamento_relato.md
        - Relato de Resultados: desenvolvimento/prototipo_alta_fidelidade/relatos_prototipo_alta.md
  - Atas de Reunião:
    - Reunião 00: atas/reuniao-00.md
    - Reunião 01: atas/reuniao-01.md
    - Reunião 02: atas/reuniao-02.md
  - Apresentações:
    - Apresentação Etapa 01: apresentacoes/etapa-01.md
    - Apresentação Etapa 02: apresentacoes/etapa-02.md
    - Apresentação Etapa 03: apresentacoes/etapa-03.md
    - Apresentação Etapa 04: apresentacoes/etapa-04.md
    - Apresentação Etapa 05: apresentacoes/etapa-05.md
    - Apresentação Etapa 6.1: apresentacoes/etapa-06.md
    - Apresentação Etapa 6.2: apresentacoes/etapa-6.2.md
    - Apresentação Etapa 07: apresentacoes/etapa-07.md
    - Apresentação Etapa 08: apresentacoes/etapa-08.md
    - Apresentação Final: apresentacoes/etapa-final.md
  - Verificação de Artefatos:
    - Artefatos Grupo 07 (Agiel):
      - Etapa 01: verificacao/grupo_7/etapa_1.md
      - Etapa 02: verificacao/grupo_7/etapa_2.md
      - Etapa 03: verificacao/grupo_7/etapa_3.md
      - Etapa 04: verificacao/grupo_7/etapa_4.md
      - Etapa 05: verificacao/grupo_7/etapa_5.md
      - Etapa 06: verificacao/grupo_7/etapa_6.md
      - Etapa 07: verificacao/grupo_7/etapa_7.md
    - Artefatos Grupo 08 (ISSnet):
      - Etapa 01: verificacao/grupo_8/etapa_1.md
      - Etapa 02: verificacao/grupo_8/etapa_2.md
      - Etapa 03: verificacao/grupo_8/etapa_3.md
      - Etapa 04: verificacao/grupo_8/etapa_4.md
      - Etapa 05: verificacao/grupo_8/etapa_5.md
