site_name: 2023.1-Delegacia-Virtual-MG

repo_name: "2023.1-Grupo07"
repo_url: "https://github.com/Interacao-Humano-Computador/2023.1-Grupo07"

theme:
  name: material
  language: "pt"
  palette:
    primary: black
    accent: white
  features:
    - navigation.tabs
  font:
    text: "Montserrat"
    code: "sans-serif"

nav:
  - Início: index.md
  - Planejamento:
    - Processo de Design: planejamento/processo_design.md
    - Escolha do Site: planejamento/escolha_do_site.md
    - Cronograma: planejamento/cronograma.md
    - Cronograma Realizado: planejamento/cronograma_realizado.md 
    - Reuniões: planejamento/reunioes.md
    - Ferramentas: planejamento/ferramentas_utilizadas.md
  - Atas de reunião:
    - Reunião 00: atas/reuniao-00.md
    - Reunião 01: atas/reuniao-01.md
  - Apresentações:
    - Etapa 01: apresentacoes/etapa-01.md
  - Análise de Requisitos:
    - Perfil do Usuário: requisitos/perfil_do_usuario.md